# Generated by Django 5.1.3 on 2024-11-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_id', models.CharField(max_length=30)),
                ('Loan_type', models.CharField(max_length=30)),
                ('Loan_amount', models.FloatField()),
                ('cust_acntno', models.IntegerField()),
                ('cust_name', models.CharField(max_length=50)),
            ],
        ),
    ]
